
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                USER_UID: ${UID:-1000}
                USER_GID: ${GID:-1000}
        image: linx_app
        container_name: linx_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker-config/php/php.ini:/usr/local/etc/php/php.ini
        depends_on:
            - mysql
            - redis
        networks:
            - linx_net

    webserver:
        image: nginx:alpine
        container_name: linx_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./docker-config/nginx/:/etc/nginx/conf.d
        depends_on:
            - app
        networks:
            - linx_net

    mysql:
        image: mysql:8.0
        container_name: linx_mysql
        restart: unless-stopped
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-linx_db}
            MYSQL_USER: ${MYSQL_USER:-linx_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - linx_mysql_data:/var/lib/mysql
            - ./docker-config/mysql/mysql.cnf:/etc/mysql/my.cnf:ro
        networks:
            - linx_net

    redis:
        image: redis:alpine
        container_name: linx_redis
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - linx_net

volumes:
    linx_mysql_data:

networks:
    linx_net:
        driver: bridge
